"""
Step 31: Report Service.
Generates signed PDF and JSON forensic reports from detection results.
Every report is SHA-256 hashed and digitally signed (Steps 87, 92).
"""

from __future__ import annotations

import hashlib
import hmac
import json
import uuid
from datetime import datetime, timezone
from typing import Any

import structlog

from ..core.config import get_settings

log = structlog.get_logger(__name__)


def _sign_report(content: bytes, secret_key: str) -> str:
    """
    Step 92: HMAC-SHA256 digital signature on report content.
    Clients can verify authenticity by recomputing with the public key.
    """
    return hmac.new(
        secret_key.encode(),
        content,
        hashlib.sha256,
    ).hexdigest()


def generate_json_report(
    job_id: str,
    result: dict[str, Any],
    user_email: str,
) -> tuple[bytes, str, str]:
    """
    Generate a structured JSON forensic report.

    Returns:
        (report_bytes, sha256_hash, signature)
    """
    settings = get_settings()

    report = {
        "report_version":  "1.0",
        "report_id":       str(uuid.uuid4()),
        "generated_at":    datetime.now(timezone.utc).isoformat(),
        "job_id":          job_id,
        "requested_by":    user_email,
        "platform":        "AuthentiGuard v0.1.0",
        "result": {
            "authenticity_score": result.get("authenticity_score"),
            "confidence":         result.get("confidence"),
            "label":              result.get("label"),
            "layer_scores":       result.get("layer_scores", {}),
            "top_signals":        result.get("evidence_summary", {}).get("top_signals", []),
            "model_attribution":  result.get("model_attribution", {}),
            "watermark_detected": result.get("evidence_summary", {}).get("watermark_detected"),
            "provenance_verified": result.get("evidence_summary", {}).get("provenance_verified"),
            "metadata_adjustment": result.get("evidence_summary", {}).get("metadata_adjustment"),
        },
        "sentence_scores": result.get("sentence_scores", []),
        "disclaimer": (
            "This report is generated by an AI system and should be reviewed by a "
            "qualified professional before being used in legal or high-stakes contexts. "
            "No AI detection system is 100% accurate."
        ),
    }

    report_bytes = json.dumps(report, indent=2, ensure_ascii=False).encode("utf-8")
    sha256 = hashlib.sha256(report_bytes).hexdigest()
    signature = _sign_report(report_bytes, settings.APP_SECRET_KEY)

    return report_bytes, sha256, signature


async def store_report(
    report_bytes: bytes,
    job_id: str,
    format: str = "json",
) -> str:
    """
    Upload the report to S3 and return its S3 key.
    """
    import boto3
    settings = get_settings()

    s3_key = f"reports/{job_id}/report.{format}"
    content_type = "application/json" if format == "json" else "application/pdf"

    kwargs: dict = {
        "region_name":           settings.AWS_REGION,
        "aws_access_key_id":     settings.AWS_ACCESS_KEY_ID,
        "aws_secret_access_key": settings.AWS_SECRET_ACCESS_KEY,
    }
    if settings.S3_ENDPOINT_URL:
        kwargs["endpoint_url"] = settings.S3_ENDPOINT_URL

    s3 = boto3.client("s3", **kwargs)
    s3.put_object(
        Bucket=settings.S3_BUCKET_REPORTS,
        Key=s3_key,
        Body=report_bytes,
        ContentType=content_type,
        ServerSideEncryption="AES256",
    )
    log.info("report_stored", s3_key=s3_key, size=len(report_bytes))
    return s3_key


async def generate_and_store_report(
    job_id: str,
    result: dict[str, Any],
    user_email: str,
) -> tuple[str, str, str]:
    """
    Full pipeline: generate → sign → store → return (s3_key, hash, signature).
    """
    report_bytes, sha256, signature = generate_json_report(job_id, result, user_email)
    s3_key = await store_report(report_bytes, job_id, format="json")
    return s3_key, sha256, signature


async def generate_pdf_report(job: Any, result: Any) -> str:
    """
    Generate a PDF report and upload to S3.
    Returns a presigned URL for download.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import mm
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    except ImportError:
        raise RuntimeError("reportlab is required for PDF generation")

    import io

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("ReportTitle", parent=styles["Title"], fontSize=18, spaceAfter=12)
    heading_style = ParagraphStyle("ReportHeading", parent=styles["Heading2"], fontSize=14, spaceAfter=8)
    body_style = styles["Normal"]

    elements = []

    # Header
    elements.append(Paragraph("AuthentiGuard Detection Report", title_style))
    elements.append(Spacer(1, 5*mm))

    # Summary table
    summary_data = [
        ["Job ID", str(job.id)],
        ["Content Type", job.content_type.value.upper()],
        ["Authenticity Score", f"{result.authenticity_score:.4f}"],
        ["Confidence", f"{result.confidence:.4f}"],
        ["Label", result.label],
        ["Processing Time", f"{result.processing_ms or 0} ms"],
        ["Analyzed At", job.completed_at.strftime("%Y-%m-%d %H:%M:%S UTC") if job.completed_at else "N/A"],
    ]
    elements.append(Paragraph("Summary", heading_style))
    t = Table(summary_data, colWidths=[120, 350])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 8*mm))

    # Layer scores
    if result.layer_scores:
        elements.append(Paragraph("Layer Scores", heading_style))
        ld = [["Layer", "Score"]]
        for layer, score in result.layer_scores.items():
            ld.append([layer, f"{score:.4f}" if isinstance(score, float) else str(score)])
        lt = Table(ld, colWidths=[200, 270])
        lt.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("LINEBELOW", (0, 0), (-1, 0), 1, HexColor("#D1D5DB")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(lt)
        elements.append(Spacer(1, 5*mm))

    # Top signals
    signals = result.evidence_summary.get("top_signals", []) if result.evidence_summary else []
    if signals:
        elements.append(Paragraph("Evidence Signals", heading_style))
        sd = [["Signal", "Value", "Weight"]]
        for s in signals:
            sd.append([s.get("signal", ""), str(s.get("value", "")), s.get("weight", "")])
        st = Table(sd, colWidths=[220, 120, 130])
        st.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("LINEBELOW", (0, 0), (-1, 0), 1, HexColor("#D1D5DB")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(st)

    # Footer
    elements.append(Spacer(1, 10*mm))
    elements.append(Paragraph(
        f"Generated by AuthentiGuard on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}. "
        "This report is AI-generated and should be reviewed by a qualified professional.",
        ParagraphStyle("Footer", parent=body_style, fontSize=8, textColor=HexColor("#9CA3AF")),
    ))

    doc.build(elements)
    pdf_bytes = buffer.getvalue()

    # Upload and generate presigned URL
    s3_key = await store_report(pdf_bytes, str(job.id), format="pdf")

    settings = get_settings()
    import boto3
    kwargs: dict = {
        "region_name":           settings.AWS_REGION,
        "aws_access_key_id":     settings.AWS_ACCESS_KEY_ID,
        "aws_secret_access_key": settings.AWS_SECRET_ACCESS_KEY,
    }
    if settings.S3_ENDPOINT_URL:
        kwargs["endpoint_url"] = settings.S3_ENDPOINT_URL

    s3 = boto3.client("s3", **kwargs)
    presigned_url = s3.generate_presigned_url(
        "get_object",
        Params={"Bucket": settings.S3_BUCKET_REPORTS, "Key": s3_key},
        ExpiresIn=3600,
    )

    result.report_s3_key = s3_key
    result.report_hash = hashlib.sha256(pdf_bytes).hexdigest()

    log.info("pdf_report_generated", job_id=str(job.id), size=len(pdf_bytes))
    return presigned_url
