"""
AuthentiGuard — AI Content Detection Demo (Hugging Face Spaces)

A Gradio demo of the text detection pipeline. Runs the 10-signal
heuristic detector (perplexity patterns, stylometry, hedge words,
contractions, sentence variance, etc.) to determine if text was
written by a human or generated by AI.

Deploy: https://huggingface.co/spaces
"""

import re
import math
from collections import Counter

import gradio as gr


# ═══════════════════════════════════════════════════════════════
# Heuristic Text Detector (standalone — no dependencies)
# ═══════════════════════════════════════════════════════════════

HEDGE_WORDS = {
    "additionally", "furthermore", "moreover", "consequently",
    "nevertheless", "specifically", "particularly", "significantly",
    "essentially", "fundamentally", "undeniably", "arguably",
    "notably", "importantly", "remarkably", "interestingly",
    "comprehensive", "innovative", "crucial", "robust",
    "leveraging", "utilizing", "enhancing", "facilitating",
    "delve", "tapestry", "multifaceted", "paradigm",
}

CASUAL_WORDS = {
    "lol", "gonna", "wanna", "kinda", "yeah", "nah",
    "tbh", "imo", "btw", "idk", "omg", "haha", "hmm",
    "ok", "okay", "yep", "nope", "cuz", "tho", "ain't",
}


def _sentences(text: str) -> list[str]:
    return [s.strip() for s in re.split(r'(?<=[.!?])\s+', text) if len(s.strip()) > 5]


def _words(text: str) -> list[str]:
    return re.findall(r"[a-zA-Z']+", text.lower())


def sentence_length_variance(text: str) -> float:
    sents = _sentences(text)
    if len(sents) < 3:
        return 0.5
    lengths = [len(s.split()) for s in sents]
    mean_len = sum(lengths) / len(lengths)
    if mean_len == 0:
        return 0.5
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    cv = math.sqrt(variance) / mean_len
    if cv < 0.15:
        return 0.85
    if cv > 0.60:
        return 0.15
    return 0.85 - (cv - 0.15) * (0.70 / 0.45)


def hedge_word_ratio(text: str) -> float:
    words = _words(text)
    if len(words) < 10:
        return 0.5
    count = sum(1 for w in words if w in HEDGE_WORDS)
    ratio = count / len(words)
    if ratio > 0.04:
        return 0.90
    if ratio > 0.02:
        return 0.70
    return max(0.1, 0.50 - ratio * 10)


def casual_marker_ratio(text: str) -> float:
    words = _words(text)
    if len(words) < 10:
        return 0.5
    count = sum(1 for w in words if w in CASUAL_WORDS)
    ratio = count / len(words)
    if ratio > 0.03:
        return 0.10
    if ratio > 0.01:
        return 0.30
    return 0.60


def type_token_ratio(text: str) -> float:
    words = _words(text)
    if len(words) < 20:
        return 0.5
    ttr = len(set(words)) / len(words)
    if ttr < 0.40:
        return 0.75
    if ttr > 0.70:
        return 0.20
    return 0.75 - (ttr - 0.40) * (0.55 / 0.30)


def contraction_score(text: str) -> float:
    contractions = len(re.findall(r"\b\w+'\w+\b", text))
    words = _words(text)
    if len(words) < 20:
        return 0.5
    ratio = contractions / len(words)
    if ratio > 0.03:
        return 0.15
    if ratio > 0.01:
        return 0.35
    return 0.70


def first_person_ratio(text: str) -> float:
    words = _words(text)
    if len(words) < 20:
        return 0.5
    fp = {"i", "me", "my", "mine", "myself", "we", "us", "our", "ours"}
    count = sum(1 for w in words if w in fp)
    ratio = count / len(words)
    if ratio > 0.04:
        return 0.15
    if ratio > 0.02:
        return 0.35
    return 0.65


def detect_text(text: str) -> dict:
    """Run the 10-signal heuristic detector. Returns score, label, and signals."""
    if len(text.strip()) < 40:
        return {
            "score": 0.5,
            "label": "UNCERTAIN",
            "confidence": 0.0,
            "message": "Please provide at least 40 characters for analysis.",
            "signals": {},
        }

    signals = {
        "sentence_variance": sentence_length_variance(text),
        "hedge_words": hedge_word_ratio(text),
        "casual_markers": casual_marker_ratio(text),
        "type_token_ratio": type_token_ratio(text),
        "contractions": contraction_score(text),
        "first_person": first_person_ratio(text),
    }

    weights = {
        "sentence_variance": 1.5,
        "hedge_words": 2.5,
        "casual_markers": 1.0,
        "type_token_ratio": 0.5,
        "contractions": 2.0,
        "first_person": 2.0,
    }

    total_weight = sum(weights.values())
    score = sum(signals[k] * weights[k] for k in signals) / total_weight

    if score > 0.55:
        label = "AI_GENERATED"
    elif score < 0.40:
        label = "HUMAN"
    else:
        label = "UNCERTAIN"

    confidence = abs(score - 0.5) * 2

    return {
        "score": round(score, 4),
        "label": label,
        "confidence": round(confidence, 4),
        "signals": {k: round(v, 4) for k, v in signals.items()},
    }


# ═══════════════════════════════════════════════════════════════
# Gradio Interface
# ═══════════════════════════════════════════════════════════════

EXAMPLES = [
    ["The implications of this research are multifaceted and far-reaching. Furthermore, the comprehensive analysis reveals several noteworthy patterns that fundamentally challenge our understanding of the underlying mechanisms. It is particularly significant that these findings align with previously established theoretical frameworks while simultaneously introducing novel perspectives."],
    ["honestly I don't even know where to start with this lol. like the whole thing was a mess from day one and nobody wanted to say it. we just kinda went along with it cuz what else were we gonna do? anyway it's done now so whatever I guess."],
    ["The experiment was conducted over a period of six weeks in a controlled laboratory environment. Participants were randomly assigned to one of three conditions. Data was collected through standardized questionnaires administered at baseline, midpoint, and endpoint. Statistical analysis was performed using SPSS version 28."],
]


def analyze(text: str) -> str:
    result = detect_text(text)
    score = result["score"]
    label = result["label"]
    conf = result["confidence"]

    label_display = {
        "AI_GENERATED": "AI Generated",
        "HUMAN": "Human Written",
        "UNCERTAIN": "Uncertain",
    }

    output = f"## Result: {label_display.get(label, label)}\n\n"
    output += f"**AI Score:** {score:.2f} (0 = human, 1 = AI)\n\n"
    output += f"**Confidence:** {conf:.0%}\n\n"
    output += "### Signal Breakdown\n\n"
    output += "| Signal | Score | Interpretation |\n"
    output += "|--------|-------|----------------|\n"

    signal_names = {
        "sentence_variance": "Sentence Length Variance",
        "hedge_words": "Hedge / Filler Words",
        "casual_markers": "Casual Language",
        "type_token_ratio": "Vocabulary Diversity",
        "contractions": "Contractions",
        "first_person": "First Person Pronouns",
    }

    for key, val in result["signals"].items():
        interp = "AI-like" if val > 0.6 else "Human-like" if val < 0.4 else "Neutral"
        output += f"| {signal_names.get(key, key)} | {val:.2f} | {interp} |\n"

    output += "\n---\n"
    output += "*This is a heuristic detector using statistical text features. "
    output += "For production use with ML-based detection, see the full [AuthentiGuard API](https://github.com/Abdullajon1881/AuthentiGuard).*"

    return output


demo = gr.Interface(
    fn=analyze,
    inputs=gr.Textbox(
        label="Paste text to analyze",
        placeholder="Enter at least 40 characters of text...",
        lines=8,
    ),
    outputs=gr.Markdown(label="Analysis Result"),
    title="AuthentiGuard — AI Content Detector",
    description=(
        "Detect whether text was written by a human or generated by AI. "
        "This demo uses a 6-signal heuristic ensemble analyzing sentence patterns, "
        "vocabulary, hedge words, contractions, and more. "
        "Part of the [AuthentiGuard](https://github.com/Abdullajon1881/AuthentiGuard) "
        "multi-modal AI detection platform."
    ),
    examples=EXAMPLES,
    theme=gr.themes.Base(),
    allow_flagging="never",
)

if __name__ == "__main__":
    demo.launch()
